#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Dia1Ex6.Resource", IsApplication=true)]

namespace Dia1Ex6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int activity = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int application_menu = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int checks = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int multiple_choice = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int simple = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int single_choice = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int two_lines = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int with_heading = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f040000
			public const int application_menu = 2130968576;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int app_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
